spring:
  application:
    name: agora
  datasource:
    url: jdbc:h2:mem:repository
    username: sa
    password: a_random_password_123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console